application: pezius
version: 2
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /tasks/tagliner
  script: tasks/tagliner.py
  login: admin

- url: /.*
  script: main.py

inbound_services:
- xmpp_message

threadsafe:
- yes